package dependencies

object Versions {
  const  val lottie: String = "3.6.1"
    const val lottie_compose: String ="1.0.0-alpha07-SNAPSHOT"

    const val work_manager: String ="2.5.0"
    const val gradle = "7.0.0-alpha12"
    const val compilesdk = 30
    const val buildTools = "30.0.2"
    const val minsdk = 26
    const val targetsdk = 30
    const val kotlin = "1.4.31"
    const val ktx = "1.3.2"
    const val dagger_hilt = "2.33-beta"
    const val   androidx_hilt = "1.0.0-alpha03"
    const val nav_components = "2.3.3"
    const val fragment_ktx = "1.3.1"
    const val material_dialogs = "3.2.1"
    const val room = "2.2.6"
    const val appcompat = "1.3.0-beta01"
    const val constraintlayout = "2.0.4"
    const val material_design = "1.3.0-alpha03"
    const val play_core = "1.7.1"
    const val play_services = "4.3.3"
    const val leak_canary = "2.0-alpha-3"
    const val swipe_refresh_layout = "1.1.0-alpha03"
    const val firebase_firestore = "21.4.2"
    const val firebase_analytics = "17.4.0"
    const val firebase_crashlytics = "2.10.1"
    const val firebase_auth = "19.3.0"
    const val espresso_core = "3.1.1"
    const val espresso_idling_resource = "3.2.0"
    const val mockk_version = "1.9.2"
    const val test_runner = "1.2.0"
    const val test_core = "1.2.0"
    const val coroutines_version = "1.3.6"
    const val coroutines_play_services = "1.3.2"
    const val lifecycle_version = "2.2.0-alpha03"
    const val retrofit2_version = "2.8.1"
    const val markdown_processor = "0.1.3"
    const val junit_jupiter_version = "5.6.0"
    const val junit_4_version = "4.12"
    const val fragment_version = "1.2.0"
    const val androidx_test_ext = "1.1.1"
    const val apollo = "2.4.0"
    const val androidx_preferences = "1.1.1"
    const val timber = "4.7.1"
    const val view_pager2 = "1.0.0"
    const  val legacy_support = "1.0.0"
    const  val converter_moshi = "2.6.2"
    const val arch_core_testing: String ="2.1.0"

}